### ISSUE TITLE
WMS bern has uri changed

### ISSUE THREAD

**Issue by tigerfoot** [ioda-net/geo-infra#23]
On 21st October Canton Bern decide to modify their uri for WMS
The new ones are 

```
http://www.geoservice.apps.be.ch/geoservice2/services/a42geo/a42geo_basiswms_d_fk/MapServer/WMSServer?
http://www.geoservice.apps.be.ch/geoservice2/services/a42geo/a42geo_grenzenwms_d_fk/MapServer/WMSServer?
http://www.geoservice.apps.be.ch/geoservice2/services/a42geo/a42geo_planungwms_d_fk/MapServer/WMSServer?
http://www.geoservice.apps.be.ch/geoservice2/services/a42geo/a42geo_umweltwms_d_fk/MapServer/WMSServer?
http://www.geoservice.apps.be.ch/geoservice2/services/a42geo/a42geo_geologiewms_d_fk/MapServer/WMSServer?
http://www.geoservice.apps.be.ch/geoservice2/services/a42geo/a42geo_gewaesserwms_d_fk/MapServer/WMSServer?
http://www.geoservice.apps.be.ch/geoservice2/services/a42geo/a42geo_transportwms_d_fk/MapServer/WMSServer?
```

**Incredible** they still don't propose the https version 

We have some references of them in documentation, and also a check of this list has to be synchronised with geo.admin.ch code.

Cool to have it merge and fixed for next devel run.

Additionnal notes : some customers infrastructure have already fixed the list by themselve, so take care of conflicts.

**Comment by Jenselme** [comment]
PR opened: https://github.com/geoadmin/mf-geoadmin3/pull/3579

**Comment by Jenselme** [comment]
Fixed a long time ago on our side. Merged in mf-geoadmin3. Closing.
